---
AWSTemplateFormatVersion: "2010-09-09"
Description: Main

Parameters:

  Environment:
    Type: String
    Description: Name of the environment

  HostedZoneId:
    Type: String
    Description: Domain hosted zone ID

Resources:

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: PublicReadGetObject
          Effect: Allow
          Principal: "*"
          Action:
            - s3:GetObject
          Resource: !Sub
                      - ${FrontendBucketArn}/*
                      - FrontendBucketArn: !GetAtt FrontendBucket.Arn

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - Fn::ImportValue: !Sub ${Environment}-Domain
          - !Sub
              - www.${Domain}
              - Domain:
                  Fn::ImportValue: !Sub ${Environment}-Domain
        CacheBehaviors:
          - AllowedMethods: # first is /api/v1 which is NOT cached at all
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # cachingdisabled https://console.aws.amazon.com/cloudfront/v2/home#/policies
            Compress: true
            OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3 # allViewer
            PathPattern: "api/v1/*"
            TargetOriginId: MainLoadBalancer
            ViewerProtocolPolicy: redirect-to-https
        DefaultCacheBehavior:
          AllowedMethods: # second is the actual frontend bucket
              - GET
              - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # cachingoptimized https://console.aws.amazon.com/cloudfront/v2/home#/policies
          Compress: true
          TargetOriginId: S3Bucket
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - ConnectionAttempts: 3
            ConnectionTimeout: 10
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginKeepaliveTimeout: 5
              OriginProtocolPolicy: https-only
              OriginReadTimeout: 30
              OriginSSLProtocols:
                - TLSv1.2
            DomainName:
              Fn::ImportValue: !Sub ${Environment}-MainLoadBalancerDnsName
            Id: MainLoadBalancer
          - ConnectionAttempts: 3
            ConnectionTimeout: 10
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginKeepaliveTimeout: 5
              OriginProtocolPolicy: http-only
              OriginReadTimeout: 30
            DomainName: !Select [2, !Split ["/", !GetAtt FrontendBucket.WebsiteURL]] #websiteurl is http://blahbla but DomainName needs to remove the protocol
            Id: S3Bucket
            OriginShield:
              Enabled: true
              OriginShieldRegion: us-east-1
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn:
            Fn::ImportValue: !Sub ${Environment}-DomainCertificate
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only

  MainNakedDNSRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        EvaluateTargetHealth: false
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: !Sub
                        - ${Domain}.
                        - Domain:
                            Fn::ImportValue: !Sub ${Environment}-Domain
      Name: !Sub
              - ${Domain}
              - Domain:
                  Fn::ImportValue: !Sub ${Environment}-Domain
      Type: A

  MainWwwDNSRecordSet:
    Type: AWS::Route53::RecordSet
    DependsOn:
      - MainNakedDNSRecordSet
    Properties:
      AliasTarget:
        DNSName:
          !Sub
            - ${Domain}
            - Domain:
                Fn::ImportValue: !Sub ${Environment}-Domain
        EvaluateTargetHealth: false
        HostedZoneId: !Ref HostedZoneId
      HostedZoneName: !Sub
                        - ${Domain}.
                        - Domain:
                            Fn::ImportValue: !Sub ${Environment}-Domain
      Name: !Sub
              - www.${Domain}
              - Domain:
                  Fn::ImportValue: !Sub ${Environment}-Domain
      Type: A

Outputs:

  CloudFrontDistribution:
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Join [ '-', [ !Ref Environment, CloudFrontDistributionId ] ]

  FrontendBucket:
    Value: !Ref FrontendBucket
    Export:
      Name: !Join [ '-', [ !Ref Environment, FrontendBucket ] ]
